# Generated by Django 4.1.1 on 2023-07-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='fio',
            field=models.CharField(default='', max_length=255, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
