# Generated by Django 4.1.1 on 2023-07-01 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_seller_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Seller.productitem'),
        ),
    ]
