# Generated by Django 4.1.1 on 2023-07-01 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Consumer.address'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='geolocate',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Consumer.geolocate'),
        ),
    ]
