# Generated by Django 4.1.1 on 2023-07-01 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer', '0003_alter_consumer_address_alter_consumer_geolocate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Consumer.address'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='geolocate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Consumer.geolocate'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Телефон'),
        ),
    ]
