# Generated by Django 4.1.1 on 2023-07-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shop_items',
            field=models.ManyToManyField(blank=True, to='Shop.shopitem', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='shop_items',
            field=models.ManyToManyField(blank=True, to='Shop.shopitem', verbose_name='Продукт'),
        ),
    ]
