# Generated by Django 4.1.1 on 2023-05-02 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shop_item',
        ),
        migrations.AddField(
            model_name='cart',
            name='shop_items',
            field=models.ManyToManyField(to='Shop.shopitem', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
